hostname: rpi-test

rcond:
  addr: 0.0.0.0:8081
  api_token: 1234567890

network:
  connections:
    # create access point and share network connection on wlan0
    - name: MyHomeWiFi
      id: MyHomeWiFi
      uuid: 222b4580-3e08-4a2c-ae5e-316bb45d44f0
      type: 802-11-wireless
      interface: wlan0
      ssid: MyHomeWiFi
      mode: ap
      band: bg
      channel: 1
      keymgmt: wpa-psk
      psk: SuperSecure
      ipv4method: shared
      ipv6method: ignore
      autoconnect: true

cluster:
  enabled: true
  log_level: INFO
  node_name: rcond-agent
  secret_key: DMXnaJUUbIBMj1Df0dPsQY+Sks1VxWTa
  advertise_addr: 0.0.0.0
  advertise_port: 7946
  bind_addr: 0.0.0.0
  bind_port: 7946
  #join:
  #  - 127.0.0.1:7946