hostname: rpi-test

rcond:
  addr: 0.0.0.0:8081
  api_token: 1234567890

network:
  connections:
    # connect to MyHomeWifi on wlan0
    - name: MyHomeWiFi
      id: MyHomeWiFi
      uuid: f09c9d1a-af3f-4726-82dd-0dd9d3358a4e
      type: 802-11-wireless
      interface: wlan0
      ssid: MyHomeWiFi
      mode: infrastructure
      keymgmt: wpa-psk
      psk: SuperSecure
      ipv4method: auto
      ipv6method: ignore
      autoconnect: true
    # TODO
    # provide DHCP on eth0
    #- name: MyThingsNetwork
    #  id: MyThingsNetwork
    #  uuid: 12df0b71-73ca-4ca2-a5f6-be20983a311d
    #  type: 802-3-ethernet
    #  interface: eth0
    #  method: shared
    #  autoconnect: true

cluster:
  enabled: true
  log_level: INFO
  node_name: rcond-agent
  secret_key: DMXnaJUUbIBMj1Df0dPsQY+Sks1VxWTa
  advertise_addr: 0.0.0.0
  advertise_port: 7946
  bind_addr: 0.0.0.0
  bind_port: 7946
  #join:
  #  - 127.0.0.1:7946