name: main

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'pkg/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'
    - name: Run build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
